name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  start_server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Prisma
        run: npm install prisma -g

      - name: Install and generate Prisma client
        run: |
          cd server
          npm install
          npx prisma generate
        # Assuming your 'prisma' folder is inside 'server' and the schema file is 'prisma/schema.prisma'

      - name: Start server
        run: |
          cd server
          npm install
          npm run start

  start_client:
    needs: start_server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Start client
        run: |
          cd client
          npm install
          npm run start

  test_server:
    needs: start_server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test server
        run: |
          cd server
          npm install
          npm run test
  test_client:
    needs: start_client
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test client
        run: |
          cd client
          npm install
          npm run test
