name: Client CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use Node.js version 16 or any desired version

      - name: Install dependencies
        run: npm install --prefix client

      - name: Install Jest
        run: npm install --prefix client jest node-fetch

      - name: Run client tests
        run: npm test --prefix client -- --env=node # Add --env=node flag here
